# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a831c1ad3f19ba407162b754d55314ed6e2a23ec88b06936599e85a5d72bd929af321a7f6cca12b5b1b04f09b2121083e935043f65d93f039e2fa06d2c1f206c

test:
  secret_key_base: 61e4689cca3dc0280a6a54c9fa73611f6040a50eba52897c791fb8308427d473170a543c89dc57ef6c3a93b171d950c280d434da6d6fea6f8233b1af9b586795

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
